### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.kind
      - azure-servicefabric.TestErrorChaosEvent.reason
      - azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="22e98-101">介绍获取混沌测试引擎中发生意外的事件时生成的混沌测试事件。</span><span class="sxs-lookup"><span data-stu-id="22e98-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="22e98-102">例如，由于群集快照不一致，实体在出错时，混沌测试找到该实体已出错已-这将会是意外的事件。</span><span class="sxs-lookup"><span data-stu-id="22e98-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="22e98-103">多态鉴别器</span><span class="sxs-lookup"><span data-stu-id="22e98-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="22e98-104">介绍为什么生成 TestErrorChaosEvent。</span><span class="sxs-lookup"><span data-stu-id="22e98-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="22e98-105">例如，混沌测试尝试一个分区出现故障，但找到分区不再具有容错能力，则 TestErrorEvent 获取生成具有原因指示分区不具备容错能力。</span><span class="sxs-lookup"><span data-stu-id="22e98-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="22e98-106">UTC 时间戳时生成该混沌测试事件。</span><span class="sxs-lookup"><span data-stu-id="22e98-106">The UTC timestamp when this Chaos event was generated.</span></span>
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent