### YamlMime:UniversalReference
ms.openlocfilehash: 80639ea90d12b3e57b99dc309a62df521d35f0f5
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/13/2018
ms.locfileid: "52032692"
items:
- uid: azure-servicefabric.ValidationFailedChaosEvent
  name: ValidationFailedChaosEvent
  fullName: ValidationFailedChaosEvent
  children:
  - azure-servicefabric.ValidationFailedChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: <span data-ttu-id="a1232-101">在验证过程与失败相对应的混沌测试事件。</span><span class="sxs-lookup"><span data-stu-id="a1232-101">Chaos event corresponding to a failure during validation.</span></span>
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.ValidationFailedChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: <span data-ttu-id="a1232-102">介绍为什么生成 ValidationFailedChaosEvent。</span><span class="sxs-lookup"><span data-stu-id="a1232-102">Describes why the ValidationFailedChaosEvent was generated.</span></span> <span data-ttu-id="a1232-103">因为多个 MaxPercentUnhealthyNodes MaxClusterStabilizationTimeout 超过不正常，则可能发生这种情况。</span><span class="sxs-lookup"><span data-stu-id="a1232-103">This may happen because more than MaxPercentUnhealthyNodes are unhealthy for more than MaxClusterStabilizationTimeout.</span></span> <span data-ttu-id="a1232-104">此原因将作为字符串 ValidationFailedChaosEvent 的原因属性中。</span><span class="sxs-lookup"><span data-stu-id="a1232-104">This reason will be in the Reason property of the ValidationFailedChaosEvent as a string.</span></span>
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
